# Generated by Django 5.2.7 on 2025-10-31 22:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketplace", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "offer_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("countered", "Countered"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="marketplace.listing",
                    ),
                ),
                (
                    "parent_offer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="counter_offers",
                        to="transactions.offer",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "offers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inquired", "Inquired"),
                            ("negotiating", "Negotiating"),
                            ("sold", "Sold"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="inquired",
                        max_length=20,
                    ),
                ),
                ("meeting_location", models.CharField(blank=True, max_length=255)),
                ("meeting_time", models.DateTimeField(blank=True, null=True)),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("notes", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="marketplace.listing",
                    ),
                ),
                (
                    "offer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaction",
                        to="transactions.offer",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MeetingLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("library", "Library"),
                            ("student_center", "Student Center"),
                            ("security_desk", "Security Desk"),
                            ("cafeteria", "Cafeteria"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("building", models.CharField(blank=True, max_length=100)),
                ("room_number", models.CharField(blank=True, max_length=50)),
                ("hours_of_operation", models.CharField(blank=True, max_length=255)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_locations",
                        to="marketplace.campus",
                    ),
                ),
            ],
            options={
                "db_table": "meeting_locations",
                "indexes": [
                    models.Index(
                        fields=["campus"], name="meeting_loc_campus__5f913b_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="meeting_loc_is_acti_1fc40d_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(fields=["listing"], name="offers_listing_ea636d_idx"),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(fields=["buyer"], name="offers_buyer_i_327b5b_idx"),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(fields=["seller"], name="offers_seller__a9b848_idx"),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(fields=["status"], name="offers_status_5a0bfa_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["listing"], name="transaction_listing_bf49f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["buyer"], name="transaction_buyer_i_56e41a_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["seller"], name="transaction_seller__083d37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["status"], name="transaction_status_505a2f_idx"),
        ),
    ]
