# Generated by Django 5.2.7 on 2025-10-31 22:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketplace", "0002_initial"),
        ("transactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dispute_type",
                    models.CharField(
                        choices=[
                            ("item_not_as_described", "Item Not As Described"),
                            ("no_show", "No Show"),
                            ("payment_issue", "Payment Issue"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_review", "In Review"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("resolution", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "complainant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes_filed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disputes_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "respondent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes_against",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disputes",
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "db_table": "disputes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DisputeEvidence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("document", "Document"),
                            ("screenshot", "Screenshot"),
                            ("message", "Message"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file_url", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "dispute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="safety.dispute",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dispute_evidence",
            },
        ),
        migrations.CreateModel(
            name="FlaggedContent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("listing", "Listing"),
                            ("message", "Message"),
                            ("user", "User"),
                            ("review", "Review"),
                        ],
                        max_length=50,
                    ),
                ),
                ("content_id", models.UUIDField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("offensive", "Offensive Content"),
                            ("scam", "Scam/Fraud"),
                            ("inappropriate", "Inappropriate"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewed", "Reviewed"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("action_taken", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "flagged_content",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("message", "New Message"),
                            ("offer", "New Offer"),
                            ("status_change", "Status Change"),
                            ("price_drop", "Price Drop"),
                            ("listing_expiring", "Listing Expiring"),
                            ("review", "New Review"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("reference_id", models.UUIDField(blank=True, null=True)),
                ("reference_type", models.CharField(blank=True, max_length=50)),
                ("is_read", models.BooleanField(default=False)),
                ("is_pushed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudyMaterial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("course_code", models.CharField(blank=True, max_length=50)),
                ("course_name", models.CharField(blank=True, max_length=255)),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("notes", "Class Notes"),
                            ("study_guide", "Study Guide"),
                            ("practice_exam", "Practice Exam"),
                            ("syllabus", "Syllabus"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file_url", models.URLField(blank=True, null=True)),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                ("file_type", models.CharField(blank=True, max_length=50)),
                ("download_count", models.IntegerField(default=0)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_materials",
                        to="marketplace.campus",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_materials_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "study_materials",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlockedUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "blocked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_by_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users_blocked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "blocked_users",
                "indexes": [
                    models.Index(
                        fields=["blocker"], name="blocked_use_blocker_56191f_idx"
                    ),
                    models.Index(
                        fields=["blocked"], name="blocked_use_blocked_850a24_idx"
                    ),
                ],
                "unique_together": {("blocker", "blocked")},
            },
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["transaction"], name="disputes_transac_6a360f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["complainant"], name="disputes_complai_d25367_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(
                fields=["respondent"], name="disputes_respond_4fac54_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispute",
            index=models.Index(fields=["status"], name="disputes_status_811094_idx"),
        ),
        migrations.AddIndex(
            model_name="disputeevidence",
            index=models.Index(
                fields=["dispute"], name="dispute_evi_dispute_c25b83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disputeevidence",
            index=models.Index(
                fields=["submitted_by"], name="dispute_evi_submitt_b11c98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flaggedcontent",
            index=models.Index(
                fields=["reporter"], name="flagged_con_reporte_dd94ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flaggedcontent",
            index=models.Index(
                fields=["content_type"], name="flagged_con_content_f5b494_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flaggedcontent",
            index=models.Index(
                fields=["content_id"], name="flagged_con_content_881789_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flaggedcontent",
            index=models.Index(fields=["status"], name="flagged_con_status_fb93e6_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["user"], name="notificatio_user_id_e78525_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["is_read"], name="notificatio_is_read_3f8c44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type"], name="notificatio_notific_19df93_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read", "-created_at"],
                name="notificatio_user_id_c4e471_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studymaterial",
            index=models.Index(
                fields=["uploader"], name="study_mater_uploade_8fda98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studymaterial",
            index=models.Index(
                fields=["campus"], name="study_mater_campus__419f46_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studymaterial",
            index=models.Index(
                fields=["course_code"], name="study_mater_course__6e5f5a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studymaterial",
            index=models.Index(
                fields=["material_type"], name="study_mater_materia_bade01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studymaterial",
            index=models.Index(
                fields=["is_approved"], name="study_mater_is_appr_97da01_idx"
            ),
        ),
    ]
