# Generated by Django 5.2.7 on 2025-10-31 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketplace", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="listingimage",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="marketplace.listing",
            ),
        ),
        migrations.AddField(
            model_name="savedsearch",
            name="campus",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="marketplace.campus",
            ),
        ),
        migrations.AddField(
            model_name="savedsearch",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="marketplace.category",
            ),
        ),
        migrations.AddField(
            model_name="savedsearch",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_searches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="textbook",
            name="listing",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="textbook",
                to="marketplace.listing",
            ),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlisted_by",
                to="marketplace.listing",
            ),
        ),
        migrations.AddField(
            model_name="wishlist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wishlist_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["slug"], name="categories_slug_b4303a_idx"),
        ),
        migrations.AddIndex(
            model_name="category",
            index=models.Index(fields=["parent"], name="categories_parent__7983b2_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["seller"], name="listings_seller__554360_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["category"], name="listings_categor_de1c95_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["campus"], name="listings_campus__b78bd6_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(fields=["status"], name="listings_status_c3eaec_idx"),
        ),
        migrations.AddIndex(
            model_name="listing",
            index=models.Index(
                fields=["-created_at"], name="listings_created_4615f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listingimage",
            index=models.Index(
                fields=["listing", "display_order"],
                name="listing_ima_listing_f49a67_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="savedsearch",
            index=models.Index(fields=["user"], name="saved_searc_user_id_af4495_idx"),
        ),
        migrations.AddIndex(
            model_name="savedsearch",
            index=models.Index(
                fields=["is_active"], name="saved_searc_is_acti_f26f88_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="textbook",
            index=models.Index(fields=["isbn_13"], name="textbooks_isbn_13_ac83c0_idx"),
        ),
        migrations.AddIndex(
            model_name="textbook",
            index=models.Index(fields=["isbn_10"], name="textbooks_isbn_10_08b565_idx"),
        ),
        migrations.AddIndex(
            model_name="textbook",
            index=models.Index(
                fields=["course_code"], name="textbooks_course__e4e19f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wishlist",
            index=models.Index(fields=["user"], name="wishlists_user_id_69623b_idx"),
        ),
        migrations.AddIndex(
            model_name="wishlist",
            index=models.Index(fields=["listing"], name="wishlists_listing_2b4678_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="wishlist",
            unique_together={("user", "listing")},
        ),
    ]
