# Generated by Django 5.2.7 on 2025-10-31 22:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("transactions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("review_text", models.TextField(blank=True)),
                (
                    "is_buyer_review",
                    models.BooleanField(
                        help_text="True if buyer reviewing seller, False if seller reviewing buyer"
                    ),
                ),
                ("is_flagged", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="transactions.transaction",
                    ),
                ),
            ],
            options={
                "db_table": "reviews",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["reviewer"], name="reviews_reviewe_965d53_idx"
                    ),
                    models.Index(
                        fields=["reviewee"], name="reviews_reviewe_0d427f_idx"
                    ),
                    models.Index(
                        fields=["reviewee", "rating"], name="reviews_reviewe_173dbf_idx"
                    ),
                ],
            },
        ),
    ]
